### ISSUE TITLE
f"a$b" is parsed as just "a"

### ISSUE THREAD

**Issue by maowtm** [modus-continens/modus#158]
https://play.modus-continens.com/#%7B%22q%22%3A%22a%22%2C%22m%22%3A%22a%20%3A-%20run(f%5C%22a%24b%5C%22).%22%7D

**Comment by mechtaev** [comment]
What is the expected behaviour here? As I understand, expansion should be only used when we have something like `a${b}`. Is it invalid syntax, or we just treat the question mark as non-special character?

**Comment by maowtm** [comment]
I was expecting it to just treat it as a literal `a$b`
