### ISSUE TITLE
Invalid operator usage does not result in proper error messages

### ISSUE THREAD

**Issue by maowtm** [modus-continens/modus#170]
![Screenshot from 2022-03-06 23-40-53](https://user-images.githubusercontent.com/47200787/156947340-182cb395-6777-4346-9783-4345c90685e2.png)

Ideally we should do type checking for operators as well...

Also TODO for me:
- [ ] Use analysis result in image generation code, so that we can just assert things inside a `::copy` is a image expression, rather than assuming this and letting `process_image` panic.

**Comment by maowtm** [comment]
Also TODO for me:
- [ ] Use analysis result in image generation code, so that we can just assert things inside a `::copy` is a image expression, rather than assuming this and letting `process_image` panic.

**Comment by thevirtuoso1973** [comment]
I think we have a decent solution for operator input/output kind checking now. Can reopen if it turns out to be insufficient.
