### ISSUE TITLE
Who's behind this project ?

### ISSUE THREAD

**Issue by sfermigier** [modus-continens/modus#208]
The website says "© 2022 University College London." so I guess it's a research project.

Could you add a link to the specific team / research project that's working on this ? And research papers, if there are any ?

**Comment by mechtaev** [comment]
@sfermigier, thank you for your interest!

The project is led by me, Sergey Mechtaev (https://mechtaev.com), and Earl T. Barr (https://earlbarr.com/). Two UCL undergraduate students, Chris Tomy @thevirtuoso1973 and Tingmao Wang @micromaomao, made significant contribution to the current version of the language. We have also published a paper about Modus:

Modus: A Datalog Dialect for Building Container Images
Chris Tomy, Tingmao Wang, Earl Barr, Sergey Mechtaev
Foundations of Software Engineering (FSE) 2022

We are currently working on the camera-ready version of the paper, and will make it public soon. Then, I will put this information on the website, and post a link to the paper here as well.

**Comment by sfermigier** [comment]
Still interested in the camera-ready version (or even a preprint).

**Comment by mechtaev** [comment]
@sfermigier, here is the camera-ready version of our paper: https://mechtaev.com/files/fse22.pdf

**Comment by mechtaev** [comment]
addressed by https://github.com/modus-continens/website/commit/46df451d8bbfec77956bca56e74ab6904602e710
