### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by maowtm** [modus-continens/modus#40]
Let's discuss this in our next meeting...

- [x] Pass along source span in AST/Literal/Proofs etc
  - [x] Decide on how to do this. Add a span to every data type in the AST (e.g. Expression, ModusClause)? Do we want to copy this along whenever we construct e.g. Literal? How to make sld solver aware of/perserve this (so that if e.g. no matching rule we can point to the source)?
  - [x] Do we want to / how do we report resolution failure? e.g.
    ```
    Failed to resolve input a("aabbb")
      a("aabbb") requires string_concat("a", X1, "aabbb") + string_concat(X1, "b", X2) + a(X2)
        taking X1 = "abbb", X2 = "abb" // maybe don't report expansion of empty rule explicitly, to make error message shorter?
          a("abb") requires string_concat("a", X3, "abb") + string_concat(X3, "b", X4) + a(X4)
            taking X3 = "bb", X4 = "b"
              a("b") requires string_concat("a", X5, "b")
                which is not satisfiable. // this line may also be: which requires X5 to be known, in the case of invalid ungrounded variables (not the case here)
    ```
    what to do with alternative rules? report them all and in each case explain why they are not satisfiable?
- [x] Do we want to report multiple errors at once? If so then we can't just panic or return error whenever something is wrong.
- [x] How do we represent errors at the time of them happening? Maybe a big enum of various types of errors that can happen? I.e. `ResolutionError { history: GoalWithHistory, reason: ResolutionErrorReason (e.g. Unsat(Literal), RequireGrounded(Vec<Variable>)) }`
- [x] For non modus errors (e.g. unable to connect to docker) maybe consider a different way of reporting them, so e.g. if one error happens abort rather than continue? Maybe consider [`thiserror`](https://docs.rs/thiserror/1.0.30/thiserror/) which makes wrapping of runtime errors easy.
- [x] Could catch some errors through semantic analysis? The advantage is that we would have the full structure of the Modusfile instead of the IR. Best case this is simply adding the tag string to the enum type `Tag`.
- [x] Output the SLD tree as a DOT file to let the user display the graph.
- [x] Better parse errors output. We can use a custom error printer. However, "Tag" errors are a bit inconvenient - I'll consider submitting a PR to `nom` to deal with this upstream.

**Comment by thevirtuoso1973** [comment]
We should have some decent error handling for 0.1 now, closing.
Future work would be graphviz/explain/proof tree related, but we can open new issues for them.
